name: Python linting and formatting checks.

on:
  workflow_dispatch:
    inputs:
      purpose:
        description: 'Purpose'
        required: true
        default: 'Manual run'
  push:
    branches: [ master ]    
  pull_request:
    branches: [ master ]
  
jobs:
  lint:
    # Lint
    runs-on: ubuntu-latest

    env:
      python-version: 3.9
      linted-dirs: basic multipython

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 isort
        
    - name: Run lints
      run: |
        flake8 ${{ env.linted-dirs }}
        black --check  ${{ env.linted-dirs }}
        isort --check  ${{ env.linted-dirs }}
